

import { Inter } from "next/font/google";
import { ClerkProvider } from '@clerk/nextjs'

import "./globals.css";
import Header from "@/components/Header";
import { Toaster } from "sonner";

export const metadata = {
  title: "GemCar AI",
  description: "Generated by arikxl",
  icons: {
    icon: "https://img.icons8.com/?size=100&id=dcQctZG93X7g&format=png&color=000000",
    shortcut: "/https://img.icons8.com/?size=100&id=dcQctZG93X7g&format=png&color=000000",
    apple: "/https://img.icons8.com/?size=100&id=dcQctZG93X7g&format=png&color=000000",// or .png, .svg, etc.
  }
};

const inter = Inter({ subsets: ["latin"] })


export default function RootLayout({ children }) {
  return (
    <ClerkProvider>

      <html lang="en">
        <body className={`${inter.className}`}>
          <Header />
          <main className="min-h-screen w-full">
            {children}
          </main>
          <Toaster richColors/>

          <footer className="bg-blue-50 py-12">
            <div className="container mx-auto px-4 text-center text-gray-600">
              <p>arikxl</p>
            </div>
          </footer>
        </body>
      </html>
    </ClerkProvider>

  );
}
