import Header from "@/components/Header";
import { Inter } from "next/font/google";
import { ClerkProvider } from '@clerk/nextjs'


import "./globals.css";

export const metadata = {
  title: "GemCar AI",
  description: "Generated by arikxl",
};

const inter = Inter({ subsets: ["latin"] })


export default function RootLayout({ children }) {
  return (
    <ClerkProvider>

      <html lang="en">
        <body className={`${inter.className}`}>
          <Header />
          <main className="min-h-screen">
            {children}
          </main>

          <footer className="bg-blue-50 py-12">
            <div className="container mx-auto px-4 text-center text-gray-600">
              <p>arikxl</p>
            </div>
          </footer>
        </body>
      </html>
    </ClerkProvider>

  );
}
